# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nursery Rhymes
email: contact@nurseryrhymes.com
description: Find all of the popular nursery rhymes here at Nursery Rhymes blog.
baseurl: "/jekyll-demo" # the subpath of your site, e.g. /blog
url: "http://splttingatms.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
